#!/bin/bash

Choised_Alarm_Name="MyAlarm1"
Choised_Alarm_Minute=`sed '1!D' /home/ilya/Шумейко/Alarm/Created_Alarms/Config_$Choised_Alarm_Name`
Choised_Alarm_Hour=`sed '2!D' /home/ilya/Шумейко/Alarm/Created_Alarms/Config_$Choised_Alarm_Name`
Choised_Alarm_Week_Day=`sed '3!D' /home/ilya/Шумейко/Alarm/Created_Alarms/Config_$Choised_Alarm_Name`
Choised_Alarm_Player=`sed '4!D' /home/ilya/Шумейко/Alarm/Created_Alarms/Config_$Choised_Alarm_Name`
Choised_Alarm_Tune=`sed '5!D' /home/ilya/Шумейко/Alarm/Created_Alarms/Config_$Choised_Alarm_Name`

cat "/home/ilya/Шумейко/Alarm/Created_Alarms/List" | grep -v "$Choised_Alarm" >> /home/ilya/Шумейко/Alarm/Created_Alarms/List2
rm /home/ilya/Шумейко/Alarm/Created_Alarms/List
mv /home/ilya/Шумейко/Alarm/Created_Alarms/List2 /home/ilya/Шумейко/Alarm/Created_Alarms/List

sed "/\$Choised_Alarm_Minute\ \$Choised_Alarm_Hour\ \*\ \*\ \$Choised_Alarm_Week_Day\ \/usr\\/bin\\/\$Choised_Alarm_Player\\ \\/home\\/ilya\\/Шумейко\\/Alarm\\/\$Choised_Alarm_Tune/d" currentjobs.txt > Alarms_Without_$$Choised_Alarm_Name.txt
crontab Alarms_Without_$$Choised_Alarm_Name.txt
rm Alarms_Without_$$Choised_Alarm_Name.txt

rm /home/ilya/Шумейко/Alarm/Created_Alarms/$Choised_Alarm_Name
